### ISSUE TITLE
Disabled auto-discovery necessary for ide-helper?

### ISSUE THREAD

**Issue by AkenRoberts** [aaronsaray/laravel-boot#1]
Laravel's package auto-discovery works by checking everything installed via Composer. If the IDE helper package is in `require-dev`, it shouldn't be installed on production, and thus shouldn't be auto-discovered.

**Comment by aaronsaray** [comment]
This has been fixed by putting don't discover in for `barryvdh/laravel-ide-helper`  thanks!

**Comment by AkenRoberts** [comment]
Sorry, I should have been more clear. I'm suggesting that disabling auto-discovery for the package may be unnecessary.

Was there a specific requirement that caused you to disable auto-discovery and add [this service provider code](https://github.com/aaronsaray/laravel-boot/blob/30daa4d525d80cc037227c45439727b27331172f/app/Providers/AppServiceProvider.php#L47-L55)? This doesn't seem to do anything different than simply adding the package to `require-dev` and letting Laravel auto-discover it.

**Comment by aaronsaray** [comment]
It's probably a good idea to look at this again. I can't remember if it was from someone installing without `--no-dev` or it was something else - but it was causing a problem on deploys of a project built with this.  I'll try to run some tests later.

**Comment by aaronsaray** [comment]
So, I fixed this.  In local, you `composer install` which brings in dev.  In other environments, you do `composer install --no-dev` which won't install the ide helper. The check was checking for `not production` to register it - which would try to do things for like testing/staging.  Instead, I changed it to `is local` for it to register now.  Thanks to @joelclermont for his help.

**Comment by AkenRoberts** [comment]
Did you figure out what the requirement for the manual service provider was in the first place? Because I'm still confused why that exists for a package that's auto-discovered. Was it just a matter of `require-dev` packages being installed on staging or something?
